version: '3.3'

services:
  db:
    image: mysql:8.2.0
    restart: always
    environment:
      MYSQL_DATABASE: 'todo_list'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
